name: Tests

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  test-osx:
    runs-on: macos-latest
     steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          which docker

  test-linux:
    runs-on: ubuntu-22.04
     steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          which docker

