name: Tests

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  test-osx:
    # runs-on: macos-latest
    runs-on: macos-12
    steps:
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          bash script.sh

  test-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          bash script.sh

