name: Tests

on:
  pull_request:
  push:

permissions:
  contents: read

env:
  DOCKER_BUILDKIT: '1'
  GO_VERSION: '1.20'

jobs:
  test-osx:
    runs-on: macos-12
     steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          which docker

  test-linux:
    runs-on: ubuntu-22.04
     steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          which docker

