name: Tests

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  test-osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          bash script.sh

  test-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          bash script.sh

